name: Cron 1 every hours

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:
    inputs:
      token:
        description: 'secret token'
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@master
    
    - name: Check current job
      id: check_run
      run: |
        out=$(wget -qO- --no-check-certificate --no-cache --timeout=18000000 --tries=3 "https://api.github.com/repos/${{github.repository}}/actions/workflows/cron_1.yml/runs")
        n=$(echo "$out" | grep -c '"in_progress"' || true)
        n1=$(echo "$out" | grep -c '"queued"' || true)
        num=$((n+n1))
        if [[ $num -gt 1 ]]; then
          echo ::set-output name=status::running
        else
          echo ::set-output name=status::no_running
        fi
      continue-on-error: true

    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Run cron rewrite
      if: success() && steps.check_run.outputs.status == 'no_running'
      run: |
        docker run \
        -e APP_NAME="${{ secrets.APP_NAME }}" \
        -e APP_TOKEN="${{ secrets.APP_TOKEN }}" \
        -e JOB_NAME="cron_rewrite" \
        -e TEST_SECRET="${{ github.event.inputs.token }}" \
        ghcr.io/admicro/ytbotserver-cli:latest
