name: Cron 1 hours

on:
  schedule:
    #0 */2 * * *
    - cron: "0 * * * *"
  
  workflow_dispatch:
    inputs:
      token:
        description: 'secret token'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 720
    steps:
    - uses: actions/checkout@master
    
    - name: Run cron rewrite
      if: success()
      run: |
        docker run \
        -e APP_NAME="${{ secrets.APP_NAME }}" \
        -e APP_TOKEN="${{ secrets.APP_TOKEN }}" \
        -e JOB_NAME="cron_rewrite" \
        ghcr.io/admicro/ytbotserver-cli:latest
