name: Cron 2 every hours

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:
    inputs:
      token:
        description: 'secret token'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
    - uses: actions/checkout@master
    
    - name: Check current job
      id: check_run
      run: |
        out=$(wget -qO- --no-check-certificate --no-cache --timeout=18000000 --tries=3 "https://api.github.com/repos/${{github.repository}}/actions/workflows/cron_1.yml/runs")
        if [[ "$out" == *'"queued"'* || "$out" == *'"in_progress"'* ]]; then
          echo ::set-output name=status::running
        else
          echo ::set-output name=status::no_running
        fi
      continue-on-error: true

    - name: Run cron rewrite
      if: success() && steps.check_run.outputs.status == 'no_running'
      run: |
        docker run \
        -e APP_NAME="${{ secrets.APP_NAME }}" \
        -e APP_TOKEN="${{ secrets.APP_TOKEN }}" \
        -e JOB_NAME="cron" \
        -e TEST_SECRET="${{ github.event.inputs.token }}" \
        ghcr.io/admicro/ytbotserver-cli:latest
