name: do job by user

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'token'
        required: true
      jobName:
        description: 'task name'     
        required: true
      jobArg1:
        description: 'job arg 1'
      jobArg2:
        description: 'job arg 2'
      jobArg3:
        description: 'job arg 3'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
    - uses: actions/checkout@master
    
    - name: Check current job
      id: check_run
      run: |
        out=$(wget -qO- --no-check-certificate --no-cache --timeout=18000000 --tries=3 "https://api.github.com/repos/${{github.repository}}/actions/workflows/cron_1.yml/runs")
        if [[ "$out" == *'"queued"'* || "$out" == *'"in_progress"'* ]]; then
          echo ::set-output name=status::running
        else
          echo ::set-output name=status::no_running
        fi
      continue-on-error: true

    - name: Run cron rewrite
      if: success() && steps.check_run.outputs.status == 'no_running'
      run: |
        docker run \
        -e APP_NAME="${{ secrets.APP_NAME }}" \
        -e APP_TOKEN="${{ github.event.inputs.token }}" \
        -e JOB_NAME="${{ github.event.inputs.jobName }}" \
        -e JOB_ARG_1="${{ github.event.inputs.jobArg1 }}" \
        -e JOB_ARG_2="${{ github.event.inputs.jobArg2 }}" \
        -e JOB_ARG_3="${{ github.event.inputs.jobArg3 }}" \
        ghcr.io/admicro/ytbotserver-cli:latest
