name: do job crawl by user

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'domain'
        required: true
      url:
        description: 'scan url'
        required: true
      db_url:
        description: 'db url'     
        required: true
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
    - uses: actions/checkout@master
    
    - name: Check current job
      id: check_run
      run: |
        out=$(wget -qO- --no-check-certificate --no-cache --timeout=18000000 --tries=3 "https://api.github.com/repos/${{github.repository}}/actions/workflows/cron_1.yml/runs")
        if [[ "$out" == *'"queued"'* || "$out" == *'"in_progress"'* ]]; then
          echo ::set-output name=status::running
        else
          echo ::set-output name=status::no_running
        fi
      continue-on-error: true

    - name: Run cron rewrite
      if: success() && steps.check_run.outputs.status == 'no_running'
      run: |
        docker run \
        -e DOMAIN="${{ github.event.inputs.domain }}" \
        -e SCAN_URL="${{ github.event.inputs.url }}" \
        -e DB_URL="${{ github.event.inputs.db_url }}" \
        ghcr.io/admicro/ytbcrawlsite:latest
